import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const leadsToSeed = [
  {
    name: "gfuweeqpf duwduud",
    email: "mjinesh40@gmail.com",
    phone: "9772187400",
    age: "88",
    level: "Intermediate",
    mode: "Online",
    status: "NEW" as const,
    source: "Imported Sheet",
    notes: "intermediate Chess Foundations 3:00 PM - 4:00 PM wednesday online 0ppppp pp",
    createdAt: new Date("2025-08-15T16:58:30"),
  },
  {
    name: "Diva Ritu",
    email: "ritika479@gmail.com",
    phone: "7030893504",
    age: "6",
    level: "Beginner",
    mode: "Online",
    status: "NEW" as const,
    source: "Imported Sheet",
    notes: "complete-beginner",
    createdAt: new Date("2025-10-23T00:06:31"),
  },
  {
    name: "Manohar Gabria Shewaram",
    email: "msgabria@gmail.com",
    phone: "7020332257",
    age: "56",
    level: "Beginner",
    mode: "Online",
    status: "NEW" as const,
    source: "Imported Sheet",
    notes: "some-knowledge",
    createdAt: new Date("2025-11-16T11:25:39"),
  },
  {
    name: "K. T. Saathvik IniyanKeerthana",
    email: "tamizhiniyankeerthana.aparna@gmail.com",
    phone: "8838406715",
    age: "4.5",
    level: "Beginner",
    mode: "Online",
    status: "NEW" as const,
    source: "Imported Sheet",
    notes: "complete-beginner",
    createdAt: new Date("2025-11-22T14:51:02"),
  },
  {
    name: "Ivaan Gupta Kumar Gupta",
    email: "jeetendra.gupta@yahoo.com",
    phone: "12488850946",
    age: "10",
    level: "Intermediate",
    mode: "Online",
    status: "NEW" as const,
    source: "Imported Sheet",
    notes: "intermediate",
    createdAt: new Date("2025-12-06T10:35:19"),
  },
  {
    name: "Jinesh mehta Jinesh",
    email: "mehtajinesh977@gmail.com",
    phone: "9772187400",
    age: "21",
    level: "Advanced",
    mode: "Online",
    status: "NEW" as const,
    source: "Imported Sheet",
    notes: "advanced",
    createdAt: new Date("2025-12-22T10:21:45"),
  },
  {
    name: "Jinesh Rupesh",
    email: "mjins@gmail.com",
    phone: "ddddd",
    age: "21",
    level: "Beginner",
    mode: "Online",
    status: "NEW" as const,
    source: "Imported Sheet",
    notes: "beginner",
    createdAt: new Date("2026-01-02T23:10:22"),
  },
  {
    name: "jinesh rupesh",
    email: "mehtajinesh977@gmail.com",
    phone: "9772187400",
    age: "21",
    level: "Beginner",
    mode: "Online",
    status: "NEW" as const,
    source: "Imported Sheet",
    notes: "beginner",
    createdAt: new Date("2026-01-05T18:55:03"),
  },
  {
    name: "amit goga",
    email: "amit_email@yahoo.com",
    phone: "98144923292",
    age: "12",
    level: "Beginner",
    mode: "Online",
    status: "NEW" as const,
    source: "Imported Sheet",
    notes: "beginner",
    createdAt: new Date("2026-01-16T02:53:43"),
  },
  {
    name: "hello jack",
    email: "mehtajinesh977@gmail.com",
    phone: "9772187400",
    age: "78",
    level: "Advanced",
    mode: "Online",
    status: "NEW" as const,
    source: "Imported Sheet",
    notes: "advanced",
    createdAt: new Date("2026-01-16T13:41:33"),
  },
  {
    name: "Kilu Ani",
    email: "anishpv02@gmail.com",
    phone: "9900514272",
    age: "-18",
    level: "Beginner",
    mode: "Online",
    status: "NEW" as const,
    source: "Imported Sheet",
    notes: "beginner",
    createdAt: new Date("2026-03-19T09:56:17"),
  },
  {
    name: "tanmaya M premila",
    email: "premi_ms@yahoo.co.in",
    phone: "9940957978",
    age: "9",
    level: "Beginner",
    mode: "Online",
    status: "NEW" as const,
    source: "Imported Sheet",
    notes: "beginner",
    createdAt: new Date("2026-03-22T13:40:35"),
  },
  {
    name: "Jo Ani",
    email: "anishpv02@gmail.com",
    phone: "9900514272",
    age: "6",
    level: "Beginner",
    mode: "Online",
    status: "NEW" as const,
    source: "Imported Sheet",
    notes: "beginner",
    createdAt: new Date("2026-03-23T03:10:07"),
  },
  {
    name: "a a",
    email: "anishpv02@gmail.com",
    phone: "222",
    age: "4",
    level: "Beginner",
    mode: "Online",
    status: "NEW" as const,
    source: "Imported Sheet",
    notes: "beginner",
    createdAt: new Date("2026-03-24T03:26:21"),
  },
  {
    name: "Aarna Tripathi Ragini mishra",
    email: "rag.ragini1991@gmail.com",
    phone: "7897133606",
    age: "8",
    level: "Intermediate",
    mode: "Online",
    status: "NEW" as const,
    source: "Imported Sheet",
    notes: "intermediate",
    createdAt: new Date("2026-04-03T10:40:21"),
  },
  {
    name: "Darpan Abc",
    email: "dsquarechessacademy@gmail.com",
    phone: "9545145740",
    age: "32",
    level: "Beginner",
    mode: "Online",
    status: "NEW" as const,
    source: "Imported Sheet",
    notes: "beginner Build confidence & discipline",
    createdAt: new Date("2026-04-04T16:38:05"),
  },
  {
    name: "Samuel Rose",
    email: "test@gmail.com",
    phone: "9192454534",
    age: "9",
    level: "Beginner",
    mode: "Online",
    status: "NEW" as const,
    source: "Imported Sheet",
    notes: "beginner",
    createdAt: new Date("2026-04-05T04:03:11"),
  },
  {
    name: "Nithin Nithin",
    email: "nithinsktr@gmail.com",
    phone: "8105246930",
    age: "11",
    level: "Beginner",
    mode: "Online",
    status: "NEW" as const,
    source: "Imported Sheet",
    notes: "Beginner",
    createdAt: new Date("2026-04-06T13:07:40"),
  },
  {
    name: "Jinesh Kumar Mehtajinesh",
    email: "mehtajinesh977@gmail.com",
    phone: "9772187400",
    age: "22",
    level: "Beginner",
    mode: "Online",
    status: "NEW" as const,
    source: "Imported Sheet",
    notes: "beginner",
    createdAt: new Date("2026-04-27T21:18:31"),
  },
  {
    name: "Magzh mYTHILI",
    email: "mythilisr24@gmail.com",
    phone: "75500051616",
    age: "-",
    level: "Beginner",
    mode: "Online",
    status: "NEW" as const,
    source: "Imported Sheet",
    notes: "beginner",
    createdAt: new Date("2026-06-23T10:22:43"),
  },
  {
    name: "jinesh mehta",
    email: "mehtajinesh977@gmail.com",
    phone: "9772187400",
    age: "21",
    level: "Intermediate",
    mode: "Online",
    status: "NEW" as const,
    source: "Imported Sheet",
    notes: "intermediate",
    createdAt: new Date("2026-07-04T18:11:32"),
  },
  {
    name: "dg et",
    email: "sangamkumarsingh555@gmail.com",
    phone: "86970679005",
    age: "-",
    level: "Beginner",
    mode: "Online",
    status: "NEW" as const,
    source: "Imported Sheet",
    notes: "beginner",
    createdAt: new Date("2026-07-04T18:16:35"),
  },
  {
    name: "Aadvitha Mallikarjun",
    email: "mallik1705@gmail.com",
    phone: "85833594097",
    age: "-",
    level: "Beginner",
    mode: "Online",
    status: "NEW" as const,
    source: "Imported Sheet",
    notes: "beginner",
    createdAt: new Date("2026-07-08T02:42:50"),
  },
  {
    name: "Adyaveer Shashi Kumar",
    email: "email2shashikumar@gmail.com",
    phone: "8605914072",
    age: "4.5",
    level: "Beginner",
    mode: "Online",
    status: "NEW" as const,
    source: "Imported Sheet",
    notes: "Beginner",
    createdAt: new Date("2026-07-27T23:36:15"),
  },
  {
    name: "Mishka Singh Anshika Pandita",
    email: "anshikap.3@gmail.com",
    phone: "90086330444",
    age: "-",
    level: "Beginner",
    mode: "Online",
    status: "NEW" as const,
    source: "Imported Sheet",
    notes: "Beginner",
    createdAt: new Date("2026-08-18T15:49:01"),
  },
  {
    name: "monika r sheethal",
    email: "monikar14m@gmail.com",
    phone: "6361074866",
    age: "21",
    level: "Beginner",
    mode: "Online",
    status: "NEW" as const,
    source: "Imported Sheet",
    notes: "Beginner",
    createdAt: new Date("2026-09-09T00:42:05"),
  },
];

async function main() {
  console.log(`Starting to seed ${leadsToSeed.length} leads...`);

  let createdCount = 0;
  for (const lead of leadsToSeed) {
    if ((prisma as any).lead) {
      await (prisma as any).lead.create({
        data: {
          name: lead.name,
          email: lead.email,
          phone: lead.phone,
          age: lead.age,
          level: lead.level,
          mode: lead.mode,
          status: lead.status,
          source: lead.source,
          notes: lead.notes,
          createdAt: lead.createdAt,
        },
      });
      createdCount++;
    } else {
      const id = `lead_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
      const insertSql = `
        INSERT INTO "Lead" ("id", "name", "age", "phone", "email", "level", "mode", "status", "source", "notes", "createdAt", "updatedAt")
        VALUES (
          '${id}',
          '${lead.name.replace(/'/g, "''")}',
          ${lead.age ? `'${lead.age.replace(/'/g, "''")}'` : "NULL"},
          '${lead.phone.replace(/'/g, "''")}',
          ${lead.email ? `'${lead.email.replace(/'/g, "''")}'` : "NULL"},
          '${lead.level.replace(/'/g, "''")}',
          '${lead.mode.replace(/'/g, "''")}',
          'NEW'::"LeadStatus",
          '${lead.source.replace(/'/g, "''")}',
          ${lead.notes ? `'${lead.notes.replace(/'/g, "''")}'` : "NULL"},
          '${lead.createdAt.toISOString()}'::timestamp,
          '${lead.createdAt.toISOString()}'::timestamp
        );
      `;
      await prisma.$executeRawUnsafe(insertSql);
      createdCount++;
    }
  }

  console.log(`Successfully seeded ${createdCount} leads into the database!`);
}

main()
  .catch((e) => {
    console.error("Error seeding leads:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
